// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/3/2026, 12:55:27 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/shwang/Documents/GitHub/ww/alcove-clone/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shwang/Documents/GitHub/ww/alcove-clone/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shwang/Documents/GitHub/ww/alcove-clone/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shwang/Documents/GitHub/ww/alcove-clone/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shwang/Documents/GitHub/ww/alcove-clone/plugins/**/*.{js,ts,mjs}","/Users/shwang/Documents/GitHub/ww/alcove-clone/composables/**/*.{js,ts,mjs}","/Users/shwang/Documents/GitHub/ww/alcove-clone/utils/**/*.{js,ts,mjs}","/Users/shwang/Documents/GitHub/ww/alcove-clone/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shwang/Documents/GitHub/ww/alcove-clone/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/shwang/Documents/GitHub/ww/alcove-clone/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/shwang/Documents/GitHub/ww/alcove-clone/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;